application: nickvelloff1
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /requestClawAccess
  script: rest.RequestClawAccess.app

#- url: /be
#  script: backends.RuntimeBackendInit.app

- url: /.*
  script: main.app
  
libraries:
- name: webapp2
  version: latest
